sudo: required

language: generic

services:
  - docker

before_install:
  - docker build -t mod05-api:$TRAVIS_BUILD_NUMBER .
  - docker tag mod05-api:$TRAVIS_BUILD_NUMBER rdtregistry.azurecr.io/mod05-api:$TRAVIS_BUILD_NUMBER
  - docker login rdtregistry.azurecr.io -u="$DOCKER_USERNAME" -p=$DOCKER_PASSWORD
  - docker push rdtregistry.azurecr.io/mod05-api:$TRAVIS_BUILD_NUMBER
  - docker run -d rdtregistry.azurecr.io/mod05-api:$TRAVIS_BUILD_NUMBER

script:
  - docker ps | grep -q mod05-api

notifications:
  email:
    recipients:
      - $EMAIL
    on_success: always
    on_failure: always