sudo: required

services:
  - docker

before_install:
  - docker build -t $DOCKER_IMAGE:$TRAVIS_COMMIT .
  - docker login rdtregistry.azurecr.io -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push $DOCKER_IMAGE:$TRAVIS_COMMIT

notifications:
  email:
    recipients:
      - $EMAIL
    on_success: never
    on_failure: always