sudo: required

services:
  - docker

before_install:
  - docker build -t mod05-api:$TRAVIS_COMMIT .
  - docker tag mod05-api:$TRAVIS_COMMIT rdtregistry.azurecr.io/mod05-api:$TRAVIS_COMMIT
  - docker login $DOCKER_REGISTRY -u="$DOCKER_USERNAME" -p=$DOCKER_PASSWORD
  - docker push rdtregistry.azurecr.io/mod05-api:$TRAVIS_COMMIT
  - docker run -d rdtregistry.azurecr.io/mod05-api:$TRAVIS_COMMIT

  script:
    - docker ps | grep -q mod05-api

notifications:
  email:
    recipients:
      - $EMAIL
    on_success: always
    on_failure: always